default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: 5432
  username: postgres

development:
  <<: *default
  database: e_shop_development

test:
  <<: *default
  database: e_shop_test

production:
  <<: *default
  database: e_shop_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
